[package]
name = "holostats-config"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
once_cell = "1.7.2"
serde = { version = "1.0.126", features = ["derive"] }
toml = "0.5.8"
